/*
 * Calcola il Rating del Fondo di Garanzia
 * Calcola il tuo Rating e verifica l'idoneità al Fondo di Garanzia
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * RatingModelXML
 */

public class RatingModelXML {
  @SerializedName("executionDate")
  private LocalDate executionDate = null;

  @SerializedName("xmlBase64")
  private String xmlBase64 = null;

  public RatingModelXML executionDate(LocalDate executionDate) {
    this.executionDate = executionDate;
    return this;
  }

   /**
   * Get executionDate
   * @return executionDate
  **/
  @Schema(description = "")
  public LocalDate getExecutionDate() {
    return executionDate;
  }

  public void setExecutionDate(LocalDate executionDate) {
    this.executionDate = executionDate;
  }

  public RatingModelXML xmlBase64(String xmlBase64) {
    this.xmlBase64 = xmlBase64;
    return this;
  }

   /**
   * Get xmlBase64
   * @return xmlBase64
  **/
  @Schema(required = true, description = "")
  public String getXmlBase64() {
    return xmlBase64;
  }

  public void setXmlBase64(String xmlBase64) {
    this.xmlBase64 = xmlBase64;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingModelXML ratingModelXML = (RatingModelXML) o;
    return Objects.equals(this.executionDate, ratingModelXML.executionDate) &&
        Objects.equals(this.xmlBase64, ratingModelXML.xmlBase64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(executionDate, xmlBase64);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingModelXML {\n");
    
    sb.append("    executionDate: ").append(toIndentedString(executionDate)).append("\n");
    sb.append("    xmlBase64: ").append(toIndentedString(xmlBase64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
