/*
 * Calcola il Rating del Fondo di Garanzia
 * Calcola il tuo Rating e verifica l'idoneità al Fondo di Garanzia
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * RatingModelCF
 */

public class RatingModelCF {
  @SerializedName("annoEsercizio")
  private Integer annoEsercizio = null;

  @SerializedName("codiceFiscale")
  private String codiceFiscale = null;

  @SerializedName("executionDate")
  private LocalDate executionDate = null;

  public RatingModelCF annoEsercizio(Integer annoEsercizio) {
    this.annoEsercizio = annoEsercizio;
    return this;
  }

   /**
   * Anno del bilancio, se non specificato usera&#x27; il primo disponibile su infocamere
   * @return annoEsercizio
  **/
  @Schema(example = "2018", description = "Anno del bilancio, se non specificato usera' il primo disponibile su infocamere")
  public Integer getAnnoEsercizio() {
    return annoEsercizio;
  }

  public void setAnnoEsercizio(Integer annoEsercizio) {
    this.annoEsercizio = annoEsercizio;
  }

  public RatingModelCF codiceFiscale(String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
    return this;
  }

   /**
   * Codice fiscale o Partita Iva dell&#x27;azienda di cui si desidera operare il calcolo rating.
   * @return codiceFiscale
  **/
  @Schema(required = true, description = "Codice fiscale o Partita Iva dell'azienda di cui si desidera operare il calcolo rating.")
  public String getCodiceFiscale() {
    return codiceFiscale;
  }

  public void setCodiceFiscale(String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
  }

  public RatingModelCF executionDate(LocalDate executionDate) {
    this.executionDate = executionDate;
    return this;
  }

   /**
   * Data di esecuzione del calcolo. Se vuota è valorizzata con la data corrente.
   * @return executionDate
  **/
  @Schema(description = "Data di esecuzione del calcolo. Se vuota è valorizzata con la data corrente.")
  public LocalDate getExecutionDate() {
    return executionDate;
  }

  public void setExecutionDate(LocalDate executionDate) {
    this.executionDate = executionDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingModelCF ratingModelCF = (RatingModelCF) o;
    return Objects.equals(this.annoEsercizio, ratingModelCF.annoEsercizio) &&
        Objects.equals(this.codiceFiscale, ratingModelCF.codiceFiscale) &&
        Objects.equals(this.executionDate, ratingModelCF.executionDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(annoEsercizio, codiceFiscale, executionDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingModelCF {\n");
    
    sb.append("    annoEsercizio: ").append(toIndentedString(annoEsercizio)).append("\n");
    sb.append("    codiceFiscale: ").append(toIndentedString(codiceFiscale)).append("\n");
    sb.append("    executionDate: ").append(toIndentedString(executionDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
