/*
 * Calcola il Rating del Fondo di Garanzia
 * Calcola il tuo Rating e verifica l'idoneità al Fondo di Garanzia
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RatingOutputModelXbrlRatingResponse
 */

public class RatingOutputModelXbrlRatingResponse {
  @SerializedName("datiAndamentali.incIndicatore0")
  private String datiAndamentaliIncIndicatore0 = null;

  @SerializedName("datiAndamentali.incIndicatore1")
  private String datiAndamentaliIncIndicatore1 = null;

  @SerializedName("datiAndamentali.incIndicatore2")
  private String datiAndamentaliIncIndicatore2 = null;

  @SerializedName("datiAndamentali.incIndicatore3")
  private String datiAndamentaliIncIndicatore3 = null;

  @SerializedName("datiAndamentali.indicatore0")
  private String datiAndamentaliIndicatore0 = null;

  @SerializedName("datiAndamentali.indicatore1")
  private String datiAndamentaliIndicatore1 = null;

  @SerializedName("datiAndamentali.indicatore2")
  private String datiAndamentaliIndicatore2 = null;

  @SerializedName("datiAndamentali.indicatore3")
  private String datiAndamentaliIndicatore3 = null;

  @SerializedName("datiAndamentali.lblIndicatore0")
  private String datiAndamentaliLblIndicatore0 = null;

  @SerializedName("datiAndamentali.lblIndicatore1")
  private String datiAndamentaliLblIndicatore1 = null;

  @SerializedName("datiAndamentali.lblIndicatore2")
  private String datiAndamentaliLblIndicatore2 = null;

  @SerializedName("datiAndamentali.lblIndicatore3")
  private String datiAndamentaliLblIndicatore3 = null;

  @SerializedName("fasciaRating")
  private String fasciaRating = null;

  @SerializedName("faultRating")
  private String faultRating = null;

  @SerializedName("incIndicatore0")
  private String incIndicatore0 = null;

  @SerializedName("incIndicatore1")
  private String incIndicatore1 = null;

  @SerializedName("incIndicatore2")
  private String incIndicatore2 = null;

  @SerializedName("incIndicatore3")
  private String incIndicatore3 = null;

  @SerializedName("incIndicatore4")
  private String incIndicatore4 = null;

  @SerializedName("incIndicatore5")
  private String incIndicatore5 = null;

  @SerializedName("incIndicatore6")
  private String incIndicatore6 = null;

  @SerializedName("incIndicatore7")
  private String incIndicatore7 = null;

  @SerializedName("indicatore0")
  private String indicatore0 = null;

  @SerializedName("indicatore1")
  private String indicatore1 = null;

  @SerializedName("indicatore2")
  private String indicatore2 = null;

  @SerializedName("indicatore3")
  private String indicatore3 = null;

  @SerializedName("indicatore4")
  private String indicatore4 = null;

  @SerializedName("indicatore5")
  private String indicatore5 = null;

  @SerializedName("indicatore6")
  private String indicatore6 = null;

  @SerializedName("indicatore7")
  private String indicatore7 = null;

  @SerializedName("infoRating")
  private String infoRating = null;

  @SerializedName("lblIndicatore0")
  private String lblIndicatore0 = null;

  @SerializedName("lblIndicatore1")
  private String lblIndicatore1 = null;

  @SerializedName("lblIndicatore2")
  private String lblIndicatore2 = null;

  @SerializedName("lblIndicatore3")
  private String lblIndicatore3 = null;

  @SerializedName("lblIndicatore4")
  private String lblIndicatore4 = null;

  @SerializedName("lblIndicatore5")
  private String lblIndicatore5 = null;

  @SerializedName("lblIndicatore6")
  private String lblIndicatore6 = null;

  @SerializedName("lblIndicatore7")
  private String lblIndicatore7 = null;

  @SerializedName("rating")
  private String rating = null;

  public RatingOutputModelXbrlRatingResponse datiAndamentaliIncIndicatore0(String datiAndamentaliIncIndicatore0) {
    this.datiAndamentaliIncIndicatore0 = datiAndamentaliIncIndicatore0;
    return this;
  }

   /**
   * Get datiAndamentaliIncIndicatore0
   * @return datiAndamentaliIncIndicatore0
  **/
  @Schema(description = "")
  public String getDatiAndamentaliIncIndicatore0() {
    return datiAndamentaliIncIndicatore0;
  }

  public void setDatiAndamentaliIncIndicatore0(String datiAndamentaliIncIndicatore0) {
    this.datiAndamentaliIncIndicatore0 = datiAndamentaliIncIndicatore0;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliIncIndicatore1(String datiAndamentaliIncIndicatore1) {
    this.datiAndamentaliIncIndicatore1 = datiAndamentaliIncIndicatore1;
    return this;
  }

   /**
   * Get datiAndamentaliIncIndicatore1
   * @return datiAndamentaliIncIndicatore1
  **/
  @Schema(description = "")
  public String getDatiAndamentaliIncIndicatore1() {
    return datiAndamentaliIncIndicatore1;
  }

  public void setDatiAndamentaliIncIndicatore1(String datiAndamentaliIncIndicatore1) {
    this.datiAndamentaliIncIndicatore1 = datiAndamentaliIncIndicatore1;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliIncIndicatore2(String datiAndamentaliIncIndicatore2) {
    this.datiAndamentaliIncIndicatore2 = datiAndamentaliIncIndicatore2;
    return this;
  }

   /**
   * Get datiAndamentaliIncIndicatore2
   * @return datiAndamentaliIncIndicatore2
  **/
  @Schema(description = "")
  public String getDatiAndamentaliIncIndicatore2() {
    return datiAndamentaliIncIndicatore2;
  }

  public void setDatiAndamentaliIncIndicatore2(String datiAndamentaliIncIndicatore2) {
    this.datiAndamentaliIncIndicatore2 = datiAndamentaliIncIndicatore2;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliIncIndicatore3(String datiAndamentaliIncIndicatore3) {
    this.datiAndamentaliIncIndicatore3 = datiAndamentaliIncIndicatore3;
    return this;
  }

   /**
   * Get datiAndamentaliIncIndicatore3
   * @return datiAndamentaliIncIndicatore3
  **/
  @Schema(description = "")
  public String getDatiAndamentaliIncIndicatore3() {
    return datiAndamentaliIncIndicatore3;
  }

  public void setDatiAndamentaliIncIndicatore3(String datiAndamentaliIncIndicatore3) {
    this.datiAndamentaliIncIndicatore3 = datiAndamentaliIncIndicatore3;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliIndicatore0(String datiAndamentaliIndicatore0) {
    this.datiAndamentaliIndicatore0 = datiAndamentaliIndicatore0;
    return this;
  }

   /**
   * Get datiAndamentaliIndicatore0
   * @return datiAndamentaliIndicatore0
  **/
  @Schema(description = "")
  public String getDatiAndamentaliIndicatore0() {
    return datiAndamentaliIndicatore0;
  }

  public void setDatiAndamentaliIndicatore0(String datiAndamentaliIndicatore0) {
    this.datiAndamentaliIndicatore0 = datiAndamentaliIndicatore0;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliIndicatore1(String datiAndamentaliIndicatore1) {
    this.datiAndamentaliIndicatore1 = datiAndamentaliIndicatore1;
    return this;
  }

   /**
   * Get datiAndamentaliIndicatore1
   * @return datiAndamentaliIndicatore1
  **/
  @Schema(description = "")
  public String getDatiAndamentaliIndicatore1() {
    return datiAndamentaliIndicatore1;
  }

  public void setDatiAndamentaliIndicatore1(String datiAndamentaliIndicatore1) {
    this.datiAndamentaliIndicatore1 = datiAndamentaliIndicatore1;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliIndicatore2(String datiAndamentaliIndicatore2) {
    this.datiAndamentaliIndicatore2 = datiAndamentaliIndicatore2;
    return this;
  }

   /**
   * Get datiAndamentaliIndicatore2
   * @return datiAndamentaliIndicatore2
  **/
  @Schema(description = "")
  public String getDatiAndamentaliIndicatore2() {
    return datiAndamentaliIndicatore2;
  }

  public void setDatiAndamentaliIndicatore2(String datiAndamentaliIndicatore2) {
    this.datiAndamentaliIndicatore2 = datiAndamentaliIndicatore2;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliIndicatore3(String datiAndamentaliIndicatore3) {
    this.datiAndamentaliIndicatore3 = datiAndamentaliIndicatore3;
    return this;
  }

   /**
   * Get datiAndamentaliIndicatore3
   * @return datiAndamentaliIndicatore3
  **/
  @Schema(description = "")
  public String getDatiAndamentaliIndicatore3() {
    return datiAndamentaliIndicatore3;
  }

  public void setDatiAndamentaliIndicatore3(String datiAndamentaliIndicatore3) {
    this.datiAndamentaliIndicatore3 = datiAndamentaliIndicatore3;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliLblIndicatore0(String datiAndamentaliLblIndicatore0) {
    this.datiAndamentaliLblIndicatore0 = datiAndamentaliLblIndicatore0;
    return this;
  }

   /**
   * Get datiAndamentaliLblIndicatore0
   * @return datiAndamentaliLblIndicatore0
  **/
  @Schema(description = "")
  public String getDatiAndamentaliLblIndicatore0() {
    return datiAndamentaliLblIndicatore0;
  }

  public void setDatiAndamentaliLblIndicatore0(String datiAndamentaliLblIndicatore0) {
    this.datiAndamentaliLblIndicatore0 = datiAndamentaliLblIndicatore0;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliLblIndicatore1(String datiAndamentaliLblIndicatore1) {
    this.datiAndamentaliLblIndicatore1 = datiAndamentaliLblIndicatore1;
    return this;
  }

   /**
   * Get datiAndamentaliLblIndicatore1
   * @return datiAndamentaliLblIndicatore1
  **/
  @Schema(description = "")
  public String getDatiAndamentaliLblIndicatore1() {
    return datiAndamentaliLblIndicatore1;
  }

  public void setDatiAndamentaliLblIndicatore1(String datiAndamentaliLblIndicatore1) {
    this.datiAndamentaliLblIndicatore1 = datiAndamentaliLblIndicatore1;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliLblIndicatore2(String datiAndamentaliLblIndicatore2) {
    this.datiAndamentaliLblIndicatore2 = datiAndamentaliLblIndicatore2;
    return this;
  }

   /**
   * Get datiAndamentaliLblIndicatore2
   * @return datiAndamentaliLblIndicatore2
  **/
  @Schema(description = "")
  public String getDatiAndamentaliLblIndicatore2() {
    return datiAndamentaliLblIndicatore2;
  }

  public void setDatiAndamentaliLblIndicatore2(String datiAndamentaliLblIndicatore2) {
    this.datiAndamentaliLblIndicatore2 = datiAndamentaliLblIndicatore2;
  }

  public RatingOutputModelXbrlRatingResponse datiAndamentaliLblIndicatore3(String datiAndamentaliLblIndicatore3) {
    this.datiAndamentaliLblIndicatore3 = datiAndamentaliLblIndicatore3;
    return this;
  }

   /**
   * Get datiAndamentaliLblIndicatore3
   * @return datiAndamentaliLblIndicatore3
  **/
  @Schema(description = "")
  public String getDatiAndamentaliLblIndicatore3() {
    return datiAndamentaliLblIndicatore3;
  }

  public void setDatiAndamentaliLblIndicatore3(String datiAndamentaliLblIndicatore3) {
    this.datiAndamentaliLblIndicatore3 = datiAndamentaliLblIndicatore3;
  }

  public RatingOutputModelXbrlRatingResponse fasciaRating(String fasciaRating) {
    this.fasciaRating = fasciaRating;
    return this;
  }

   /**
   * Get fasciaRating
   * @return fasciaRating
  **/
  @Schema(description = "")
  public String getFasciaRating() {
    return fasciaRating;
  }

  public void setFasciaRating(String fasciaRating) {
    this.fasciaRating = fasciaRating;
  }

  public RatingOutputModelXbrlRatingResponse faultRating(String faultRating) {
    this.faultRating = faultRating;
    return this;
  }

   /**
   * Get faultRating
   * @return faultRating
  **/
  @Schema(description = "")
  public String getFaultRating() {
    return faultRating;
  }

  public void setFaultRating(String faultRating) {
    this.faultRating = faultRating;
  }

  public RatingOutputModelXbrlRatingResponse incIndicatore0(String incIndicatore0) {
    this.incIndicatore0 = incIndicatore0;
    return this;
  }

   /**
   * Get incIndicatore0
   * @return incIndicatore0
  **/
  @Schema(description = "")
  public String getIncIndicatore0() {
    return incIndicatore0;
  }

  public void setIncIndicatore0(String incIndicatore0) {
    this.incIndicatore0 = incIndicatore0;
  }

  public RatingOutputModelXbrlRatingResponse incIndicatore1(String incIndicatore1) {
    this.incIndicatore1 = incIndicatore1;
    return this;
  }

   /**
   * Get incIndicatore1
   * @return incIndicatore1
  **/
  @Schema(description = "")
  public String getIncIndicatore1() {
    return incIndicatore1;
  }

  public void setIncIndicatore1(String incIndicatore1) {
    this.incIndicatore1 = incIndicatore1;
  }

  public RatingOutputModelXbrlRatingResponse incIndicatore2(String incIndicatore2) {
    this.incIndicatore2 = incIndicatore2;
    return this;
  }

   /**
   * Get incIndicatore2
   * @return incIndicatore2
  **/
  @Schema(description = "")
  public String getIncIndicatore2() {
    return incIndicatore2;
  }

  public void setIncIndicatore2(String incIndicatore2) {
    this.incIndicatore2 = incIndicatore2;
  }

  public RatingOutputModelXbrlRatingResponse incIndicatore3(String incIndicatore3) {
    this.incIndicatore3 = incIndicatore3;
    return this;
  }

   /**
   * Get incIndicatore3
   * @return incIndicatore3
  **/
  @Schema(description = "")
  public String getIncIndicatore3() {
    return incIndicatore3;
  }

  public void setIncIndicatore3(String incIndicatore3) {
    this.incIndicatore3 = incIndicatore3;
  }

  public RatingOutputModelXbrlRatingResponse incIndicatore4(String incIndicatore4) {
    this.incIndicatore4 = incIndicatore4;
    return this;
  }

   /**
   * Get incIndicatore4
   * @return incIndicatore4
  **/
  @Schema(description = "")
  public String getIncIndicatore4() {
    return incIndicatore4;
  }

  public void setIncIndicatore4(String incIndicatore4) {
    this.incIndicatore4 = incIndicatore4;
  }

  public RatingOutputModelXbrlRatingResponse incIndicatore5(String incIndicatore5) {
    this.incIndicatore5 = incIndicatore5;
    return this;
  }

   /**
   * Get incIndicatore5
   * @return incIndicatore5
  **/
  @Schema(description = "")
  public String getIncIndicatore5() {
    return incIndicatore5;
  }

  public void setIncIndicatore5(String incIndicatore5) {
    this.incIndicatore5 = incIndicatore5;
  }

  public RatingOutputModelXbrlRatingResponse incIndicatore6(String incIndicatore6) {
    this.incIndicatore6 = incIndicatore6;
    return this;
  }

   /**
   * Get incIndicatore6
   * @return incIndicatore6
  **/
  @Schema(description = "")
  public String getIncIndicatore6() {
    return incIndicatore6;
  }

  public void setIncIndicatore6(String incIndicatore6) {
    this.incIndicatore6 = incIndicatore6;
  }

  public RatingOutputModelXbrlRatingResponse incIndicatore7(String incIndicatore7) {
    this.incIndicatore7 = incIndicatore7;
    return this;
  }

   /**
   * Get incIndicatore7
   * @return incIndicatore7
  **/
  @Schema(description = "")
  public String getIncIndicatore7() {
    return incIndicatore7;
  }

  public void setIncIndicatore7(String incIndicatore7) {
    this.incIndicatore7 = incIndicatore7;
  }

  public RatingOutputModelXbrlRatingResponse indicatore0(String indicatore0) {
    this.indicatore0 = indicatore0;
    return this;
  }

   /**
   * Get indicatore0
   * @return indicatore0
  **/
  @Schema(description = "")
  public String getIndicatore0() {
    return indicatore0;
  }

  public void setIndicatore0(String indicatore0) {
    this.indicatore0 = indicatore0;
  }

  public RatingOutputModelXbrlRatingResponse indicatore1(String indicatore1) {
    this.indicatore1 = indicatore1;
    return this;
  }

   /**
   * Get indicatore1
   * @return indicatore1
  **/
  @Schema(description = "")
  public String getIndicatore1() {
    return indicatore1;
  }

  public void setIndicatore1(String indicatore1) {
    this.indicatore1 = indicatore1;
  }

  public RatingOutputModelXbrlRatingResponse indicatore2(String indicatore2) {
    this.indicatore2 = indicatore2;
    return this;
  }

   /**
   * Get indicatore2
   * @return indicatore2
  **/
  @Schema(description = "")
  public String getIndicatore2() {
    return indicatore2;
  }

  public void setIndicatore2(String indicatore2) {
    this.indicatore2 = indicatore2;
  }

  public RatingOutputModelXbrlRatingResponse indicatore3(String indicatore3) {
    this.indicatore3 = indicatore3;
    return this;
  }

   /**
   * Get indicatore3
   * @return indicatore3
  **/
  @Schema(description = "")
  public String getIndicatore3() {
    return indicatore3;
  }

  public void setIndicatore3(String indicatore3) {
    this.indicatore3 = indicatore3;
  }

  public RatingOutputModelXbrlRatingResponse indicatore4(String indicatore4) {
    this.indicatore4 = indicatore4;
    return this;
  }

   /**
   * Get indicatore4
   * @return indicatore4
  **/
  @Schema(description = "")
  public String getIndicatore4() {
    return indicatore4;
  }

  public void setIndicatore4(String indicatore4) {
    this.indicatore4 = indicatore4;
  }

  public RatingOutputModelXbrlRatingResponse indicatore5(String indicatore5) {
    this.indicatore5 = indicatore5;
    return this;
  }

   /**
   * Get indicatore5
   * @return indicatore5
  **/
  @Schema(description = "")
  public String getIndicatore5() {
    return indicatore5;
  }

  public void setIndicatore5(String indicatore5) {
    this.indicatore5 = indicatore5;
  }

  public RatingOutputModelXbrlRatingResponse indicatore6(String indicatore6) {
    this.indicatore6 = indicatore6;
    return this;
  }

   /**
   * Get indicatore6
   * @return indicatore6
  **/
  @Schema(description = "")
  public String getIndicatore6() {
    return indicatore6;
  }

  public void setIndicatore6(String indicatore6) {
    this.indicatore6 = indicatore6;
  }

  public RatingOutputModelXbrlRatingResponse indicatore7(String indicatore7) {
    this.indicatore7 = indicatore7;
    return this;
  }

   /**
   * Get indicatore7
   * @return indicatore7
  **/
  @Schema(description = "")
  public String getIndicatore7() {
    return indicatore7;
  }

  public void setIndicatore7(String indicatore7) {
    this.indicatore7 = indicatore7;
  }

  public RatingOutputModelXbrlRatingResponse infoRating(String infoRating) {
    this.infoRating = infoRating;
    return this;
  }

   /**
   * Get infoRating
   * @return infoRating
  **/
  @Schema(description = "")
  public String getInfoRating() {
    return infoRating;
  }

  public void setInfoRating(String infoRating) {
    this.infoRating = infoRating;
  }

  public RatingOutputModelXbrlRatingResponse lblIndicatore0(String lblIndicatore0) {
    this.lblIndicatore0 = lblIndicatore0;
    return this;
  }

   /**
   * Get lblIndicatore0
   * @return lblIndicatore0
  **/
  @Schema(description = "")
  public String getLblIndicatore0() {
    return lblIndicatore0;
  }

  public void setLblIndicatore0(String lblIndicatore0) {
    this.lblIndicatore0 = lblIndicatore0;
  }

  public RatingOutputModelXbrlRatingResponse lblIndicatore1(String lblIndicatore1) {
    this.lblIndicatore1 = lblIndicatore1;
    return this;
  }

   /**
   * Get lblIndicatore1
   * @return lblIndicatore1
  **/
  @Schema(description = "")
  public String getLblIndicatore1() {
    return lblIndicatore1;
  }

  public void setLblIndicatore1(String lblIndicatore1) {
    this.lblIndicatore1 = lblIndicatore1;
  }

  public RatingOutputModelXbrlRatingResponse lblIndicatore2(String lblIndicatore2) {
    this.lblIndicatore2 = lblIndicatore2;
    return this;
  }

   /**
   * Get lblIndicatore2
   * @return lblIndicatore2
  **/
  @Schema(description = "")
  public String getLblIndicatore2() {
    return lblIndicatore2;
  }

  public void setLblIndicatore2(String lblIndicatore2) {
    this.lblIndicatore2 = lblIndicatore2;
  }

  public RatingOutputModelXbrlRatingResponse lblIndicatore3(String lblIndicatore3) {
    this.lblIndicatore3 = lblIndicatore3;
    return this;
  }

   /**
   * Get lblIndicatore3
   * @return lblIndicatore3
  **/
  @Schema(description = "")
  public String getLblIndicatore3() {
    return lblIndicatore3;
  }

  public void setLblIndicatore3(String lblIndicatore3) {
    this.lblIndicatore3 = lblIndicatore3;
  }

  public RatingOutputModelXbrlRatingResponse lblIndicatore4(String lblIndicatore4) {
    this.lblIndicatore4 = lblIndicatore4;
    return this;
  }

   /**
   * Get lblIndicatore4
   * @return lblIndicatore4
  **/
  @Schema(description = "")
  public String getLblIndicatore4() {
    return lblIndicatore4;
  }

  public void setLblIndicatore4(String lblIndicatore4) {
    this.lblIndicatore4 = lblIndicatore4;
  }

  public RatingOutputModelXbrlRatingResponse lblIndicatore5(String lblIndicatore5) {
    this.lblIndicatore5 = lblIndicatore5;
    return this;
  }

   /**
   * Get lblIndicatore5
   * @return lblIndicatore5
  **/
  @Schema(description = "")
  public String getLblIndicatore5() {
    return lblIndicatore5;
  }

  public void setLblIndicatore5(String lblIndicatore5) {
    this.lblIndicatore5 = lblIndicatore5;
  }

  public RatingOutputModelXbrlRatingResponse lblIndicatore6(String lblIndicatore6) {
    this.lblIndicatore6 = lblIndicatore6;
    return this;
  }

   /**
   * Get lblIndicatore6
   * @return lblIndicatore6
  **/
  @Schema(description = "")
  public String getLblIndicatore6() {
    return lblIndicatore6;
  }

  public void setLblIndicatore6(String lblIndicatore6) {
    this.lblIndicatore6 = lblIndicatore6;
  }

  public RatingOutputModelXbrlRatingResponse lblIndicatore7(String lblIndicatore7) {
    this.lblIndicatore7 = lblIndicatore7;
    return this;
  }

   /**
   * Get lblIndicatore7
   * @return lblIndicatore7
  **/
  @Schema(description = "")
  public String getLblIndicatore7() {
    return lblIndicatore7;
  }

  public void setLblIndicatore7(String lblIndicatore7) {
    this.lblIndicatore7 = lblIndicatore7;
  }

  public RatingOutputModelXbrlRatingResponse rating(String rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @Schema(description = "")
  public String getRating() {
    return rating;
  }

  public void setRating(String rating) {
    this.rating = rating;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingOutputModelXbrlRatingResponse ratingOutputModelXbrlRatingResponse = (RatingOutputModelXbrlRatingResponse) o;
    return Objects.equals(this.datiAndamentaliIncIndicatore0, ratingOutputModelXbrlRatingResponse.datiAndamentaliIncIndicatore0) &&
        Objects.equals(this.datiAndamentaliIncIndicatore1, ratingOutputModelXbrlRatingResponse.datiAndamentaliIncIndicatore1) &&
        Objects.equals(this.datiAndamentaliIncIndicatore2, ratingOutputModelXbrlRatingResponse.datiAndamentaliIncIndicatore2) &&
        Objects.equals(this.datiAndamentaliIncIndicatore3, ratingOutputModelXbrlRatingResponse.datiAndamentaliIncIndicatore3) &&
        Objects.equals(this.datiAndamentaliIndicatore0, ratingOutputModelXbrlRatingResponse.datiAndamentaliIndicatore0) &&
        Objects.equals(this.datiAndamentaliIndicatore1, ratingOutputModelXbrlRatingResponse.datiAndamentaliIndicatore1) &&
        Objects.equals(this.datiAndamentaliIndicatore2, ratingOutputModelXbrlRatingResponse.datiAndamentaliIndicatore2) &&
        Objects.equals(this.datiAndamentaliIndicatore3, ratingOutputModelXbrlRatingResponse.datiAndamentaliIndicatore3) &&
        Objects.equals(this.datiAndamentaliLblIndicatore0, ratingOutputModelXbrlRatingResponse.datiAndamentaliLblIndicatore0) &&
        Objects.equals(this.datiAndamentaliLblIndicatore1, ratingOutputModelXbrlRatingResponse.datiAndamentaliLblIndicatore1) &&
        Objects.equals(this.datiAndamentaliLblIndicatore2, ratingOutputModelXbrlRatingResponse.datiAndamentaliLblIndicatore2) &&
        Objects.equals(this.datiAndamentaliLblIndicatore3, ratingOutputModelXbrlRatingResponse.datiAndamentaliLblIndicatore3) &&
        Objects.equals(this.fasciaRating, ratingOutputModelXbrlRatingResponse.fasciaRating) &&
        Objects.equals(this.faultRating, ratingOutputModelXbrlRatingResponse.faultRating) &&
        Objects.equals(this.incIndicatore0, ratingOutputModelXbrlRatingResponse.incIndicatore0) &&
        Objects.equals(this.incIndicatore1, ratingOutputModelXbrlRatingResponse.incIndicatore1) &&
        Objects.equals(this.incIndicatore2, ratingOutputModelXbrlRatingResponse.incIndicatore2) &&
        Objects.equals(this.incIndicatore3, ratingOutputModelXbrlRatingResponse.incIndicatore3) &&
        Objects.equals(this.incIndicatore4, ratingOutputModelXbrlRatingResponse.incIndicatore4) &&
        Objects.equals(this.incIndicatore5, ratingOutputModelXbrlRatingResponse.incIndicatore5) &&
        Objects.equals(this.incIndicatore6, ratingOutputModelXbrlRatingResponse.incIndicatore6) &&
        Objects.equals(this.incIndicatore7, ratingOutputModelXbrlRatingResponse.incIndicatore7) &&
        Objects.equals(this.indicatore0, ratingOutputModelXbrlRatingResponse.indicatore0) &&
        Objects.equals(this.indicatore1, ratingOutputModelXbrlRatingResponse.indicatore1) &&
        Objects.equals(this.indicatore2, ratingOutputModelXbrlRatingResponse.indicatore2) &&
        Objects.equals(this.indicatore3, ratingOutputModelXbrlRatingResponse.indicatore3) &&
        Objects.equals(this.indicatore4, ratingOutputModelXbrlRatingResponse.indicatore4) &&
        Objects.equals(this.indicatore5, ratingOutputModelXbrlRatingResponse.indicatore5) &&
        Objects.equals(this.indicatore6, ratingOutputModelXbrlRatingResponse.indicatore6) &&
        Objects.equals(this.indicatore7, ratingOutputModelXbrlRatingResponse.indicatore7) &&
        Objects.equals(this.infoRating, ratingOutputModelXbrlRatingResponse.infoRating) &&
        Objects.equals(this.lblIndicatore0, ratingOutputModelXbrlRatingResponse.lblIndicatore0) &&
        Objects.equals(this.lblIndicatore1, ratingOutputModelXbrlRatingResponse.lblIndicatore1) &&
        Objects.equals(this.lblIndicatore2, ratingOutputModelXbrlRatingResponse.lblIndicatore2) &&
        Objects.equals(this.lblIndicatore3, ratingOutputModelXbrlRatingResponse.lblIndicatore3) &&
        Objects.equals(this.lblIndicatore4, ratingOutputModelXbrlRatingResponse.lblIndicatore4) &&
        Objects.equals(this.lblIndicatore5, ratingOutputModelXbrlRatingResponse.lblIndicatore5) &&
        Objects.equals(this.lblIndicatore6, ratingOutputModelXbrlRatingResponse.lblIndicatore6) &&
        Objects.equals(this.lblIndicatore7, ratingOutputModelXbrlRatingResponse.lblIndicatore7) &&
        Objects.equals(this.rating, ratingOutputModelXbrlRatingResponse.rating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datiAndamentaliIncIndicatore0, datiAndamentaliIncIndicatore1, datiAndamentaliIncIndicatore2, datiAndamentaliIncIndicatore3, datiAndamentaliIndicatore0, datiAndamentaliIndicatore1, datiAndamentaliIndicatore2, datiAndamentaliIndicatore3, datiAndamentaliLblIndicatore0, datiAndamentaliLblIndicatore1, datiAndamentaliLblIndicatore2, datiAndamentaliLblIndicatore3, fasciaRating, faultRating, incIndicatore0, incIndicatore1, incIndicatore2, incIndicatore3, incIndicatore4, incIndicatore5, incIndicatore6, incIndicatore7, indicatore0, indicatore1, indicatore2, indicatore3, indicatore4, indicatore5, indicatore6, indicatore7, infoRating, lblIndicatore0, lblIndicatore1, lblIndicatore2, lblIndicatore3, lblIndicatore4, lblIndicatore5, lblIndicatore6, lblIndicatore7, rating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingOutputModelXbrlRatingResponse {\n");
    
    sb.append("    datiAndamentaliIncIndicatore0: ").append(toIndentedString(datiAndamentaliIncIndicatore0)).append("\n");
    sb.append("    datiAndamentaliIncIndicatore1: ").append(toIndentedString(datiAndamentaliIncIndicatore1)).append("\n");
    sb.append("    datiAndamentaliIncIndicatore2: ").append(toIndentedString(datiAndamentaliIncIndicatore2)).append("\n");
    sb.append("    datiAndamentaliIncIndicatore3: ").append(toIndentedString(datiAndamentaliIncIndicatore3)).append("\n");
    sb.append("    datiAndamentaliIndicatore0: ").append(toIndentedString(datiAndamentaliIndicatore0)).append("\n");
    sb.append("    datiAndamentaliIndicatore1: ").append(toIndentedString(datiAndamentaliIndicatore1)).append("\n");
    sb.append("    datiAndamentaliIndicatore2: ").append(toIndentedString(datiAndamentaliIndicatore2)).append("\n");
    sb.append("    datiAndamentaliIndicatore3: ").append(toIndentedString(datiAndamentaliIndicatore3)).append("\n");
    sb.append("    datiAndamentaliLblIndicatore0: ").append(toIndentedString(datiAndamentaliLblIndicatore0)).append("\n");
    sb.append("    datiAndamentaliLblIndicatore1: ").append(toIndentedString(datiAndamentaliLblIndicatore1)).append("\n");
    sb.append("    datiAndamentaliLblIndicatore2: ").append(toIndentedString(datiAndamentaliLblIndicatore2)).append("\n");
    sb.append("    datiAndamentaliLblIndicatore3: ").append(toIndentedString(datiAndamentaliLblIndicatore3)).append("\n");
    sb.append("    fasciaRating: ").append(toIndentedString(fasciaRating)).append("\n");
    sb.append("    faultRating: ").append(toIndentedString(faultRating)).append("\n");
    sb.append("    incIndicatore0: ").append(toIndentedString(incIndicatore0)).append("\n");
    sb.append("    incIndicatore1: ").append(toIndentedString(incIndicatore1)).append("\n");
    sb.append("    incIndicatore2: ").append(toIndentedString(incIndicatore2)).append("\n");
    sb.append("    incIndicatore3: ").append(toIndentedString(incIndicatore3)).append("\n");
    sb.append("    incIndicatore4: ").append(toIndentedString(incIndicatore4)).append("\n");
    sb.append("    incIndicatore5: ").append(toIndentedString(incIndicatore5)).append("\n");
    sb.append("    incIndicatore6: ").append(toIndentedString(incIndicatore6)).append("\n");
    sb.append("    incIndicatore7: ").append(toIndentedString(incIndicatore7)).append("\n");
    sb.append("    indicatore0: ").append(toIndentedString(indicatore0)).append("\n");
    sb.append("    indicatore1: ").append(toIndentedString(indicatore1)).append("\n");
    sb.append("    indicatore2: ").append(toIndentedString(indicatore2)).append("\n");
    sb.append("    indicatore3: ").append(toIndentedString(indicatore3)).append("\n");
    sb.append("    indicatore4: ").append(toIndentedString(indicatore4)).append("\n");
    sb.append("    indicatore5: ").append(toIndentedString(indicatore5)).append("\n");
    sb.append("    indicatore6: ").append(toIndentedString(indicatore6)).append("\n");
    sb.append("    indicatore7: ").append(toIndentedString(indicatore7)).append("\n");
    sb.append("    infoRating: ").append(toIndentedString(infoRating)).append("\n");
    sb.append("    lblIndicatore0: ").append(toIndentedString(lblIndicatore0)).append("\n");
    sb.append("    lblIndicatore1: ").append(toIndentedString(lblIndicatore1)).append("\n");
    sb.append("    lblIndicatore2: ").append(toIndentedString(lblIndicatore2)).append("\n");
    sb.append("    lblIndicatore3: ").append(toIndentedString(lblIndicatore3)).append("\n");
    sb.append("    lblIndicatore4: ").append(toIndentedString(lblIndicatore4)).append("\n");
    sb.append("    lblIndicatore5: ").append(toIndentedString(lblIndicatore5)).append("\n");
    sb.append("    lblIndicatore6: ").append(toIndentedString(lblIndicatore6)).append("\n");
    sb.append("    lblIndicatore7: ").append(toIndentedString(lblIndicatore7)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
