/*
 * Calcola il Rating del Fondo di Garanzia
 * Calcola il tuo Rating e verifica l'idoneità al Fondo di Garanzia
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.LocalDate;

import java.io.IOException;
import java.util.Objects;
/**
 * RatingModelXBRL
 */


public class RatingModelXBRL {
  @SerializedName("codiceAteco")
  private String codiceAteco = null;

  @SerializedName("executionDate")
  private LocalDate executionDate = null;

  /**
   * Gets or Sets formaGiuridica
   */
  @JsonAdapter(FormaGiuridicaEnum.Adapter.class)
  public enum FormaGiuridicaEnum {
    AF("AF"),
    AC("AC"),
    AI("AI"),
    PA("PA"),
    AT("AT"),
    AM("AM"),
    AP("AP"),
    AR("AR"),
    AL("AL"),
    LL("LL"),
    AZ("AZ"),
    CE("CE"),
    CF("CF"),
    CO("CO"),
    CC("CC"),
    CZ("CZ"),
    CR("CR"),
    CM("CM"),
    CS("CS"),
    RC("RC"),
    OO("OO"),
    EN("EN"),
    ES("ES"),
    ED("ED"),
    EE("EE"),
    ER("ER"),
    EI("EI"),
    EM("EM"),
    EC("EC"),
    EP("EP"),
    EL("EL"),
    FO("FO"),
    FI("FI"),
    GE("GE"),
    IF("IF"),
    DI("DI"),
    IC("IC"),
    ID("ID"),
    IR("IR"),
    MA("MA"),
    PF("PF"),
    PC("PC"),
    PS("PS"),
    SR("SR"),
    RR("RR"),
    SU("SU"),
    RS("RS"),
    SA("SA"),
    CN("CN"),
    SL("SL"),
    OS("OS"),
    AE("AE"),
    AN("AN"),
    SO("SO"),
    SC("SC"),
    CI("CI"),
    CL("CL"),
    OC("OC"),
    SG("SG"),
    SS("SS"),
    SF("SF"),
    SM("SM"),
    SD("SD"),
    AA("AA"),
    AS("AS"),
    SN("SN"),
    SI("SI"),
    SZ("SZ"),
    SP("SP"),
    AU("AU"),
    SE("SE"),
    SV("SV"),
    ST("ST");

    private String value;

    FormaGiuridicaEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FormaGiuridicaEnum fromValue(String text) {
      for (FormaGiuridicaEnum b : FormaGiuridicaEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FormaGiuridicaEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FormaGiuridicaEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FormaGiuridicaEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FormaGiuridicaEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("formaGiuridica")
  private FormaGiuridicaEnum formaGiuridica = null;

  @SerializedName("regimeContabilita")
  private String regimeContabilita = null;

  @SerializedName("xbrl1Base64")
  private String xbrl1Base64 = null;

  @SerializedName("xbrl2Base64")
  private String xbrl2Base64 = null;

  public RatingModelXBRL codiceAteco(String codiceAteco) {
    this.codiceAteco = codiceAteco;
    return this;
  }

   /**
   * Get codiceAteco
   * @return codiceAteco
  **/
  @Schema(required = true, description = "")
  public String getCodiceAteco() {
    return codiceAteco;
  }

  public void setCodiceAteco(String codiceAteco) {
    this.codiceAteco = codiceAteco;
  }

  public RatingModelXBRL executionDate(LocalDate executionDate) {
    this.executionDate = executionDate;
    return this;
  }

   /**
   * Get executionDate
   * @return executionDate
  **/
  @Schema(description = "")
  public LocalDate getExecutionDate() {
    return executionDate;
  }

  public void setExecutionDate(LocalDate executionDate) {
    this.executionDate = executionDate;
  }

  public RatingModelXBRL formaGiuridica(FormaGiuridicaEnum formaGiuridica) {
    this.formaGiuridica = formaGiuridica;
    return this;
  }

   /**
   * Get formaGiuridica
   * @return formaGiuridica
  **/
  @Schema(example = "AF", required = true, description = "")
  public FormaGiuridicaEnum getFormaGiuridica() {
    return formaGiuridica;
  }

  public void setFormaGiuridica(FormaGiuridicaEnum formaGiuridica) {
    this.formaGiuridica = formaGiuridica;
  }

  public RatingModelXBRL regimeContabilita(String regimeContabilita) {
    this.regimeContabilita = regimeContabilita;
    return this;
  }

   /**
   * Get regimeContabilita
   * @return regimeContabilita
  **/
  @Schema(required = true, description = "")
  public String getRegimeContabilita() {
    return regimeContabilita;
  }

  public void setRegimeContabilita(String regimeContabilita) {
    this.regimeContabilita = regimeContabilita;
  }

  public RatingModelXBRL xbrl1Base64(String xbrl1Base64) {
    this.xbrl1Base64 = xbrl1Base64;
    return this;
  }

   /**
   * Get xbrl1Base64
   * @return xbrl1Base64
  **/
  @Schema(required = true, description = "")
  public String getXbrl1Base64() {
    return xbrl1Base64;
  }

  public void setXbrl1Base64(String xbrl1Base64) {
    this.xbrl1Base64 = xbrl1Base64;
  }

  public RatingModelXBRL xbrl2Base64(String xbrl2Base64) {
    this.xbrl2Base64 = xbrl2Base64;
    return this;
  }

   /**
   * Get xbrl2Base64
   * @return xbrl2Base64
  **/
  @Schema(required = true, description = "")
  public String getXbrl2Base64() {
    return xbrl2Base64;
  }

  public void setXbrl2Base64(String xbrl2Base64) {
    this.xbrl2Base64 = xbrl2Base64;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingModelXBRL ratingModelXBRL = (RatingModelXBRL) o;
    return Objects.equals(this.codiceAteco, ratingModelXBRL.codiceAteco) &&
        Objects.equals(this.executionDate, ratingModelXBRL.executionDate) &&
        Objects.equals(this.formaGiuridica, ratingModelXBRL.formaGiuridica) &&
        Objects.equals(this.regimeContabilita, ratingModelXBRL.regimeContabilita) &&
        Objects.equals(this.xbrl1Base64, ratingModelXBRL.xbrl1Base64) &&
        Objects.equals(this.xbrl2Base64, ratingModelXBRL.xbrl2Base64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiceAteco, executionDate, formaGiuridica, regimeContabilita, xbrl1Base64, xbrl2Base64);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingModelXBRL {\n");
    
    sb.append("    codiceAteco: ").append(toIndentedString(codiceAteco)).append("\n");
    sb.append("    executionDate: ").append(toIndentedString(executionDate)).append("\n");
    sb.append("    formaGiuridica: ").append(toIndentedString(formaGiuridica)).append("\n");
    sb.append("    regimeContabilita: ").append(toIndentedString(regimeContabilita)).append("\n");
    sb.append("    xbrl1Base64: ").append(toIndentedString(xbrl1Base64)).append("\n");
    sb.append("    xbrl2Base64: ").append(toIndentedString(xbrl2Base64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
