/*
 * Calcola il Rating del Fondo di Garanzia
 * Calcola il tuo Rating e verifica l'idoneità al Fondo di Garanzia
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.Configuration;
import io.swagger.client.auth.ApiKeyAuth;
import io.swagger.client.model.*;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.threeten.bp.LocalDate;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * API tests for RatingApi
 */

public class RatingApiTest {

    private final RatingApi api = new RatingApi();

    /**
     * Calcola il Rating con il Codice Fiscale
     *
     * Il servizio permette di rendere fruibili, per le sole società di capitali, i risultati della procedura di calcolo denominato “Mcc Rating” per la determinazione della probabilità di inadempimento dei soggetti beneficiari finali.  In input all&#x27;api è necessario il solo codice fiscale dell&#x27;impresa, sono invece opzionali l&#x27;esercizio finanziario per l&#x27;estrazione dei bilanci e la data di esecuzione del calcolo.  Per il significato degli indicatori presenti nell&#x27;output si rimanda alle &lt;a target &#x3D;\&quot;_blank\&quot; href &#x3D; \&quot;http://www.fondidigaranzia.it/wp-content/uploads/2019/02/D.O.-riforma-20190213-con-nuove-sezioni.pdf\&quot; &gt;disposizioni operative del fondo. Parte IX - MODULO ECONOMICO – FINANZIARIO e ANDAMENTALE”&lt;/a&gt; 
     *
     * @throws ApiException
     *          if the Api call fails
     */

    private Properties prop;

    @Before
    public void loadProperties() throws IOException {
        prop = new Properties();
        String propFile = "application.properties";
        InputStream inputStream = getClass().getClassLoader().getResourceAsStream(propFile);
        if (inputStream != null) {
            prop.load(inputStream);
        } else{
            throw new FileNotFoundException("Property file "+propFile+" not found");
        }
    }

    @Test
    public void calcoloRatingCFTest() throws ApiException {
        ApiClient defaultClient = Configuration.getDefaultApiClient();

        // Configure API key authorization: apiKeyHeader
        ApiKeyAuth apiKeyHeader = (ApiKeyAuth) defaultClient.getAuthentication("apiKeyHeader");
        apiKeyHeader.setApiKey(prop.getProperty("api.key"));

        RatingApi apiInstance = new RatingApi();
        String authorization = prop.getProperty("api.autorization");
        RatingModelCF body = new RatingModelCF(); // RatingModelCF | ratingModelCF
        body.setAnnoEsercizio(2019);
        body.setExecutionDate(LocalDate.of(2021,5,10));
        body.setCodiceFiscale("13355541007");
        try {
            RatingOutputModel result = apiInstance.calcoloRatingCF(authorization, body);
            System.out.println(result);
            Assert.assertTrue(result != null);
        } catch (ApiException e) {
            System.err.println("Exception when calling RatingApi#calcoloRatingCF");
            e.printStackTrace();
        }

    }
    /**
     * Calcola il Rating con il Codice Fiscale e opzionali i dati Credit Bureau, Centrale Rischi ed eventi pregiudizievoli
     *
     * Il servizio permette di rendere fruibili, per le sole società di capitali, i risultati della procedura di calcolo denominato “Mcc Rating” per la determinazione della probabilità di inadempimento dei soggetti beneficiari finali. E&#x27; possibile specificare in input anche i dati dati di Credit Bureau, Centrale Rischi ed eventi pregiudizievoli. Il servizio restituisce i dati del calcolo del Rating ed il bilancio utilizzato per effettuare la valutazione in formato xbrl.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void calcoloRatingCF2Test() throws ApiException {
        String authorization = null;
        Object body = null;
        RatingOutputModelXbrl response = api.calcoloRatingCF2(authorization, body);

        // TODO: test validations
    }
    /**
     * Calcola il Rating con il file XBRL
     *
     * Il servizio permette di rendere fruibili, per le sole società di capitali, i risultati della procedura di calcolo denominato “Mcc Rating” per la determinazione della probabilità di inadempimento dei soggetti beneficiari finali.  In input all&#x27;api, oltre alle informazioni anagrafiche dell&#x27;azienda, sono necessair i bilanci defli ultimi due anni in formato XRBL.  Per il significato degli indicatori presenti nell&#x27;output si rimanda alle &lt;a target &#x3D;\&quot;_blank\&quot; href &#x3D; \&quot;http://www.fondidigaranzia.it/wp-content/uploads/2019/02/D.O.-riforma-20190213-con-nuove-sezioni.pdf\&quot; &gt;disposizioni operative del fondo. Parte IX - MODULO ECONOMICO – FINANZIARIO e ANDAMENTALE”&lt;/a&gt; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void calcoloRatingXBRLTest() throws ApiException {
        String authorization = null;
        RatingModelXBRL body = null;
        RatingOutputModel response = api.calcoloRatingXBRL(authorization, body);

        // TODO: test validations
    }
    /**
     * Calcola il Rating con il file XML
     *
     * Il servizio permette di rendere fruibili i risultati della procedura di calcolo denominato “Mcc Rating” per la determinazione della probabilità di inadempimento dei soggetti beneficiari finali.  Download: &lt;a href&#x3D;\&quot;https://mccfilehostingprod.blob.core.windows.net/api-rating/MCC_Rating_Xml_Validazione.xsd?sp&#x3D;r&amp;st&#x3D;2021-05-28T07:53:47Z&amp;se&#x3D;2021-05-28T15:53:47Z&amp;spr&#x3D;https&amp;sv&#x3D;2020-02-10&amp;sr&#x3D;b&amp;sig&#x3D;mZyLWw%2F7QyEeDzbd8i6%2Bnexr4K6CdRFsTl6gXaTPQb0%3D\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Bilancio XSD&lt;/a&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void calcoloRatingXMLTest() throws ApiException {
        ApiClient defaultClient = Configuration.getDefaultApiClient();

        // Configure API key authorization: apiKeyHeader
        ApiKeyAuth apiKeyHeader = (ApiKeyAuth) defaultClient.getAuthentication("apiKeyHeader");
        apiKeyHeader.setApiKey(prop.getProperty("api.key"));

        RatingApi apiInstance = new RatingApi();
        String authorization = prop.getProperty("api.autorization");
        RatingModelXML body = new RatingModelXML();
        body.executionDate(LocalDate.of(2018,05,2));
        String xml = prop.getProperty("api.test.xml");
        body.setXmlBase64(xml);
        try {
            RatingOutputModel result = apiInstance.calcoloRatingXML(authorization, body);
            System.out.println(result);
            Assert.assertTrue(result != null);
        } catch (ApiException e) {
            System.err.println("Exception when calling RatingApi#calcoloRatingXML");
            e.printStackTrace();
        }
    }
}
